# .streamlit/secrets.toml
[endpoints]
usdinr_url = "https://api.frankfurter.app/latest?from=USD&to=INR"
gold_api_url = "https://finnhub.io/api/v1/quote"

[market_data]
finnhub_key = "d8imct9r01qmfrvhpvcgd8imct9r01qmfrvhpvd0"

[market_data]
api_key = "UX724B88G7HW9G3H"
base_url = "https://www.alphavantage.co/query"
finnhub_key="d8imct9r01qmfrvhpvcgd8imct9r01qmfrvhpvd0"